<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="8" passed="2" failed="6" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-24T11:47:21 IST" name="Suite" finished-at="2022-12-24T11:48:11 IST" duration-ms="49860">
    <groups>
    </groups>
    <test started-at="2022-12-24T11:47:21 IST" name="SanityTest" finished-at="2022-12-24T11:48:11 IST" duration-ms="49811">
      <class name="ebankingLoginTest.EBankingLoginTest">
        <test-method is-config="true" signature="initDriver()[pri:0, instance:ebankingLoginTest.EBankingLoginTest@792b749c]" started-at="2022-12-24T11:47:21 IST" name="initDriver" finished-at="2022-12-24T11:47:32 IST" duration-ms="10434" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method signature="testResetUserIdAndpassword(java.lang.String,java.lang.String)[pri:1, instance:ebankingLoginTest.EBankingLoginTest@792b749c]" started-at="2022-12-24T11:47:32 IST" name="testResetUserIdAndpassword" finished-at="2022-12-24T11:47:33 IST" duration-ms="1046" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr4392563738]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[qApEnumrtvvf]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResetUserIdAndpassword -->
        <test-method signature="testLoginWithValidUserIdAndPassword(java.lang.String,java.lang.String)[pri:2, instance:ebankingLoginTest.EBankingLoginTest@792b749c]" started-at="2022-12-24T11:47:33 IST" name="testLoginWithValidUserIdAndPassword" finished-at="2022-12-24T11:47:34 IST" duration-ms="798" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr439256]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[qApEnum]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginWithValidUserIdAndPassword -->
        <test-method signature="testLogoutFromAccount()[pri:3, instance:ebankingLoginTest.EBankingLoginTest@792b749c]" started-at="2022-12-24T11:47:34 IST" name="testLogoutFromAccount" finished-at="2022-12-24T11:47:34 IST" duration-ms="37" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception accured white testing testLogoutFromAccount:unexpected alert open: {Alert text : User or Password is not valid}
  (Session info: chrome=108.0.5359.125): User or Password is not valid
Build info: version: '4.2.2', revision: '683ccb65d6'
System info: host: 'AZMAL', ip: '192.168.0.101', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '18.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [19592f431b545e7e038bf07daa0f46d7, findElement {using=xpath, value=//a[text()='Log out']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 108.0.5359.125, chrome: {chromedriverVersion: 108.0.5359.71 (1e0e3868ee06..., userDataDir: C:\Users\syedm\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:62953}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:62953/devtoo..., se:cdpVersion: 108.0.5359.125, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 19592f431b545e7e038bf07daa0f46d7]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception accured white testing testLogoutFromAccount:unexpected alert open: {Alert text : User or Password is not valid}
  (Session info: chrome=108.0.5359.125): User or Password is not valid
Build info: version: '4.2.2', revision: '683ccb65d6'
System info: host: 'AZMAL', ip: '192.168.0.101', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '18.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [19592f431b545e7e038bf07daa0f46d7, findElement {using=xpath, value=//a[text()='Log out']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 108.0.5359.125, chrome: {chromedriverVersion: 108.0.5359.71 (1e0e3868ee06..., userDataDir: C:\Users\syedm\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:62953}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:62953/devtoo..., se:cdpVersion: 108.0.5359.125, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 19592f431b545e7e038bf07daa0f46d7
at org.testng.Assert.fail(Assert.java:110)
at ebankingLoginTest.EBankingLoginTest.testLogoutFromAccount(EBankingLoginTest.java:76)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogoutFromAccount -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:ebankingLoginTest.EBankingLoginTest@792b749c]" started-at="2022-12-24T11:47:34 IST" name="quitDriver" finished-at="2022-12-24T11:47:34 IST" duration-ms="241" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- ebankingLoginTest.EBankingLoginTest -->
      <class name="ebankingPracticeTest.NewAccountTest">
        <test-method is-config="true" signature="initDriver()[pri:0, instance:ebankingPracticeTest.NewAccountTest@61c4eee0]" started-at="2022-12-24T11:47:41 IST" name="initDriver" finished-at="2022-12-24T11:47:47 IST" duration-ms="5394" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method signature="testNewAccountWithInvalidData(java.lang.String,java.lang.String)[pri:1, instance:ebankingPracticeTest.NewAccountTest@61c4eee0]" started-at="2022-12-24T11:47:47 IST" name="testNewAccountWithInvalidData" finished-at="2022-12-24T11:47:48 IST" duration-ms="1532" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr439256]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[qApEnum]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception occured while testing testNewAccountWithInvalidData:[Ljava.lang.StackTraceElement;@184823ed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception occured while testing testNewAccountWithInvalidData:[Ljava.lang.StackTraceElement;@184823ed
at org.testng.Assert.fail(Assert.java:110)
at ebankingPracticeTest.NewAccountTest.testNewAccountWithInvalidData(NewAccountTest.java:47)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNewAccountWithInvalidData -->
        <test-method signature="testNewAccountWithValidData(java.lang.String,java.lang.String)[pri:2, instance:ebankingPracticeTest.NewAccountTest@61c4eee0]" started-at="2022-12-24T11:47:48 IST" name="testNewAccountWithValidData" finished-at="2022-12-24T11:47:57 IST" duration-ms="8393" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr439256]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[qApEnum]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception occured while testing testNewAccountWithValidData:[Ljava.lang.StackTraceElement;@5aa62ee7]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception occured while testing testNewAccountWithValidData:[Ljava.lang.StackTraceElement;@5aa62ee7
at org.testng.Assert.fail(Assert.java:110)
at ebankingPracticeTest.NewAccountTest.testNewAccountWithValidData(NewAccountTest.java:75)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNewAccountWithValidData -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:ebankingPracticeTest.NewAccountTest@61c4eee0]" started-at="2022-12-24T11:47:57 IST" name="quitDriver" finished-at="2022-12-24T11:47:57 IST" duration-ms="252" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- ebankingPracticeTest.NewAccountTest -->
      <class name="ebankingPracticeTest.DepositTest">
        <test-method is-config="true" signature="initDriver()[pri:0, instance:ebankingPracticeTest.DepositTest@6f10d5b6]" started-at="2022-12-24T11:47:57 IST" name="initDriver" finished-at="2022-12-24T11:48:03 IST" duration-ms="6350" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method signature="testDepositWithInvalidData(java.lang.String,java.lang.String)[pri:1, instance:ebankingPracticeTest.DepositTest@6f10d5b6]" started-at="2022-12-24T11:48:03 IST" name="testDepositWithInvalidData" finished-at="2022-12-24T11:48:04 IST" duration-ms="864" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr439256]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[qApEnum]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception while testing testDepositWithInvalidData:unexpected alert open: {Alert text : User or Password is not valid}
  (Session info: chrome=108.0.5359.125): User or Password is not valid
Build info: version: '4.2.2', revision: '683ccb65d6'
System info: host: 'AZMAL', ip: '192.168.0.101', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '18.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [bc410da9f5283c04859816e25ec222bd, findElement {using=xpath, value=//a[text()='Deposit']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 108.0.5359.125, chrome: {chromedriverVersion: 108.0.5359.71 (1e0e3868ee06..., userDataDir: C:\Users\syedm\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:63219}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:63219/devtoo..., se:cdpVersion: 108.0.5359.125, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: bc410da9f5283c04859816e25ec222bd]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception while testing testDepositWithInvalidData:unexpected alert open: {Alert text : User or Password is not valid}
  (Session info: chrome=108.0.5359.125): User or Password is not valid
Build info: version: '4.2.2', revision: '683ccb65d6'
System info: host: 'AZMAL', ip: '192.168.0.101', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '18.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [bc410da9f5283c04859816e25ec222bd, findElement {using=xpath, value=//a[text()='Deposit']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 108.0.5359.125, chrome: {chromedriverVersion: 108.0.5359.71 (1e0e3868ee06..., userDataDir: C:\Users\syedm\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:63219}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:63219/devtoo..., se:cdpVersion: 108.0.5359.125, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: bc410da9f5283c04859816e25ec222bd
at org.testng.Assert.fail(Assert.java:110)
at ebankingPracticeTest.DepositTest.testDepositWithInvalidData(DepositTest.java:47)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDepositWithInvalidData -->
        <test-method signature="testDepositWithValidData()[pri:1, instance:ebankingPracticeTest.DepositTest@6f10d5b6]" started-at="2022-12-24T11:48:04 IST" name="testDepositWithValidData" finished-at="2022-12-24T11:48:11 IST" duration-ms="6608" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception while testing testDepositWithValidData:no such element: Unable to locate element: {"method":"xpath","selector":"//input[@name='accountno']"}
  (Session info: chrome=108.0.5359.125)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.2.2', revision: '683ccb65d6'
System info: host: 'AZMAL', ip: '192.168.0.101', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '18.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [bc410da9f5283c04859816e25ec222bd, findElement {using=xpath, value=//input[@name='accountno']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 108.0.5359.125, chrome: {chromedriverVersion: 108.0.5359.71 (1e0e3868ee06..., userDataDir: C:\Users\syedm\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:63219}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:63219/devtoo..., se:cdpVersion: 108.0.5359.125, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: bc410da9f5283c04859816e25ec222bd]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception while testing testDepositWithValidData:no such element: Unable to locate element: {"method":"xpath","selector":"//input[@name='accountno']"}
  (Session info: chrome=108.0.5359.125)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.2.2', revision: '683ccb65d6'
System info: host: 'AZMAL', ip: '192.168.0.101', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '18.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [bc410da9f5283c04859816e25ec222bd, findElement {using=xpath, value=//input[@name='accountno']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 108.0.5359.125, chrome: {chromedriverVersion: 108.0.5359.71 (1e0e3868ee06..., userDataDir: C:\Users\syedm\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:63219}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:63219/devtoo..., se:cdpVersion: 108.0.5359.125, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: bc410da9f5283c04859816e25ec222bd
at org.testng.Assert.fail(Assert.java:110)
at ebankingPracticeTest.DepositTest.testDepositWithValidData(DepositTest.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDepositWithValidData -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:ebankingPracticeTest.DepositTest@6f10d5b6]" started-at="2022-12-24T11:48:11 IST" name="quitDriver" finished-at="2022-12-24T11:48:11 IST" duration-ms="193" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- ebankingPracticeTest.DepositTest -->
      <class name="ebankingPracticeTest.AddNewCustomerTest">
        <test-method is-config="true" signature="initDriver()[pri:0, instance:ebankingPracticeTest.AddNewCustomerTest@35841320]" started-at="2022-12-24T11:47:34 IST" name="initDriver" finished-at="2022-12-24T11:47:39 IST" duration-ms="5476" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method signature="testAddNewCustomerFieldsWithValidDetails(java.lang.String,java.lang.String)[pri:1, instance:ebankingPracticeTest.AddNewCustomerTest@35841320]" started-at="2022-12-24T11:47:39 IST" name="testAddNewCustomerFieldsWithValidDetails" finished-at="2022-12-24T11:47:41 IST" duration-ms="1904" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr439256]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[qApEnum]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception accured white testing testAddNewCustomerFieldsWithValidDetails:[Ljava.lang.StackTraceElement;@6909f6be]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception accured white testing testAddNewCustomerFieldsWithValidDetails:[Ljava.lang.StackTraceElement;@6909f6be
at org.testng.Assert.fail(Assert.java:110)
at ebankingPracticeTest.AddNewCustomerTest.testAddNewCustomerFieldsWithValidDetails(AddNewCustomerTest.java:53)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddNewCustomerFieldsWithValidDetails -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:ebankingPracticeTest.AddNewCustomerTest@35841320]" started-at="2022-12-24T11:47:41 IST" name="quitDriver" finished-at="2022-12-24T11:47:41 IST" duration-ms="193" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- ebankingPracticeTest.AddNewCustomerTest -->
    </test> <!-- SanityTest -->
    <test started-at="2022-12-24T11:48:11 IST" name="RegressionTest" finished-at="2022-12-24T11:48:11 IST" duration-ms="1">
    </test> <!-- RegressionTest -->
  </suite> <!-- Suite -->
</testng-results>
